#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    # Write your code here
    zeros = len([item for item in arr if item == 0])
    pos = len([item for item in arr if item > 0])
    neg = len([item for item in arr if item < 0])
    print(pos/len(arr))
    print(neg/len(arr))
    print(zeros/len(arr))

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
